### ISSUE TITLE
Thrown objects collide with other throwable objects

### ISSUE THREAD

**Issue by XanderMooney** [XanderMooney/Jauntlet#11]
Need to figure out a good way to get thrown objects not to collide with each other - moving them to the ignore collision layer seems to cause a graphical bug where they become invisible

**Comment by ponyfan88** [comment]
Adding low priority since it's not particularly game breaking

**Comment by XanderMooney** [comment]
With the fix to "IgnoreCollision" now being rendered by the camera, this could be fixed now, although bullets would also now not hit the objects. To be determined if thats a good thing or not.
