### ISSUE TITLE
Thrown objects sometimes go through walls

### ISSUE THREAD

**Issue by XanderMooney** [XanderMooney/Jauntlet#7]
This is due to how the position offset works (which is mandatory for the holding animations that are now in the works), meaning that while the object is being held it can be shoved into a wall, then if thrown into the wall, it will go straight through. This is due to how OnTriggerEnter2D works, meaning it has already entered so its not triggered.

I tried switching to OnTriggerStay2D, but it causes the object to plunge its side into the wall, because of the 1 frame delay on OnTriggerStay2D.

more research will need to be done to find a good fix or imbetween... maybe we just need both?

**Comment by XanderMooney** [comment]
potential fix, but not closing quite yet (github auto closed)

**Comment by ponyfan88** [comment]
this was already fixed?????
